CREATE TABLE `users`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `age` TINYINT(3) UNSIGNED NOT NULL,
    `country` VARCHAR(255) NOT NULL,
    `social_media_url` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL default CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY(`email`)
);
